### ISSUE TITLE
Issue blocking agregore-gemini-render

### ISSUE THREAD

**Issue by KyGost** [RangerMauve/gemini-to-html#2]
[`render.js` `L1`](https://github.com/RangerMauve/gemini-to-html/blob/71639ae4ca41b590968a3c69da2a70d6cc2ff7ad/render.js#L1) uses a require, this prevents the script from being used directly by a browser.

Is the code needed? Can we do it another way?

This is preventing merge on agregore-gemini-render.

**Comment by RangerMauve** [comment]
Personally, I think it'd be best to use a generate a bundle with browserify bundle if you're running the code in an environment without Node support.

**Comment by KyGost** [comment]
Resolved
