### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by vinipsmaker** [RangerMauve/gemini-to-html#4]
It'd be nice if there was a Firefox extension to preview/render Gemtext in Firefox. For instance, something like this (but for Gemtext): https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/

**Comment by RangerMauve** [comment]
Yeah! This library might be cool as a basis for something like that. 😁

If somebody ends up implementing such an extension I'd be happy to add it to the README or something.
